In [1]:
#Escriba una funcion que tome y y x como entradas y devuelva estimaciones de β0 y β1 utilizando 
#la metodologıa de mınimos cuadrados.

import wooldridge as woo
import numpy as np

woo.dataWoo('ceosal1', description=True)
ceosal1 = woo.dataWoo('ceosal1')

x = ceosal1['roe']
# print(x)
y = ceosal1['salary']
# print(y)
# ingredientes para la formula de MCO:
print(np.cov(x, y))
# cov_xy = np.cov(x, y)[1, 0]  # acceder a 2. fila y 1. columna de la matriz de covarianza
# print(cov_xy)
# var_x = np.var(x, ddof=1)
# x_bar = np.mean(x)
# y_bar = np.mean(y)



name of dataset: ceosal1
no of variables: 12
no of observations: 209

+----------+-------------------------------+
| variable | label                         |
+----------+-------------------------------+
| salary   | 1990 salary, thousands $      |
| pcsalary | % change salary, 89-90        |
| sales    | 1990 firm sales, millions $   |
| roe      | return on equity, 88-90 avg   |
| pcroe    | % change roe, 88-90           |
| ros      | return on firm's stock, 88-90 |
| indus    | =1 if industrial firm         |
| finance  | =1 if financial firm          |
| consprod | =1 if consumer product firm   |
| utility  | =1 if transport. or utilties  |
| lsalary  | natural log of salary         |
| lsales   | natural log of sales          |
+----------+-------------------------------+

I took a random sample of data reported in the May 6, 1991 issue of
Businessweek.
[[7.25649898e+01 1.34253840e+03]
 [1.34253840e+03 1.88333164e+06]]


In [2]:
#cálculo manual de los coeficientes MCO:
b1 = cov_xy / var_x
b0 = y_bar - b1 * x_bar
print(f'b1: {b1}\n')
print(f'b0: {b0}\n')

NameError: name 'cov_xy' is not defined

In [3]:
import numpy as np
np.random.seed (37)
x = np.random.rand(1000)
x

array([9.44496603e-01, 4.64098174e-01, 1.92795029e-01, 5.81894877e-01,
       6.20084210e-01, 6.84224017e-01, 1.03437555e-01, 7.45475766e-01,
       2.81979070e-01, 7.53424587e-01, 7.92705630e-01, 6.27400596e-01,
       4.43488844e-01, 9.63465352e-01, 8.97066554e-01, 1.96804288e-01,
       5.95951133e-01, 5.73376945e-01, 7.04949354e-01, 9.29262018e-01,
       5.12298289e-02, 1.34811989e-01, 1.17028506e-01, 3.64724761e-01,
       8.03410838e-01, 9.70242721e-01, 3.32979259e-01, 4.78419874e-01,
       1.78937448e-01, 9.02534488e-01, 7.63575685e-01, 1.98860530e-01,
       3.65686168e-01, 5.95582272e-01, 4.00942676e-02, 8.24627983e-01,
       6.40271383e-01, 1.91370108e-02, 8.06038372e-01, 4.04892652e-01,
       3.60388437e-03, 4.65233416e-01, 3.36850918e-01, 5.35399413e-01,
       9.36791598e-01, 8.76554650e-01, 7.52074360e-01, 4.64996178e-01,
       7.03900655e-01, 3.87213468e-02, 6.79701277e-01, 4.18979619e-01,
       9.02858461e-01, 9.45161632e-01, 9.77051241e-01, 5.80674337e-01,
      

In [4]:
y = 0.5 + 1.8 * x
y

array([2.20009389, 1.33537671, 0.84703105, 1.54741078, 1.61615158,
       1.73160323, 0.6861876 , 1.84185638, 1.00756233, 1.85616426,
       1.92687013, 1.62932107, 1.29827992, 2.23423763, 2.1147198 ,
       0.85424772, 1.57271204, 1.5320785 , 1.76890884, 2.17267163,
       0.59221369, 0.74266158, 0.71065131, 1.15650457, 1.94613951,
       2.2464369 , 1.09936267, 1.36115577, 0.82208741, 2.12456208,
       1.87443623, 0.85794895, 1.1582351 , 1.57204809, 0.57216968,
       1.98433037, 1.65248849, 0.53444662, 1.95086907, 1.22880677,
       0.50648699, 1.33742015, 1.10633165, 1.46371894, 2.18622488,
       2.07779837, 1.85373385, 1.33699312, 1.76702118, 0.56969842,
       1.7234623 , 1.25416331, 2.12514523, 2.20129094, 2.25869223,
       1.54521381, 2.25564042, 1.5571128 , 1.0964324 , 1.35547122,
       1.29771012, 1.81408497, 1.63333817, 2.05351042, 1.10485601,
       1.74335393, 1.25349044, 0.86839259, 0.57134187, 1.57553723,
       2.19196525, 2.23790151, 2.01251903, 2.16597877, 1.55147

In [ ]:
import wooldridge as woo
import statsmodels.formula.api as smf
import matplotlib.pyplot as plt

# Regresión de MCO:
reg = smf.ols(formula='y ~ x', data=ceosal1)
results = reg.fit()

# scatter plot and fitted values:
plt.plot('roe', 'salary', data=ceosal1, color='blue', marker='o', linestyle='')
plt.plot(ceosal1['roe'], results.fittedvalues, color='black', linestyle='-')
plt.ylabel('salary')
plt.xlabel('roe')
plt.savefig('Regresion_Salary_Roe')